# Generated by Django 6.0.3 on 2026-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.RemoveField(
            model_name='album',
            name='featured_artists',
        ),
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('movie', 'Movie Soundtrack'), ('album', 'Independent Album'), ('single', 'Single'), ('ep', 'EP')], default='album', max_length=20),
        ),
        migrations.AddField(
            model_name='album',
            name='movie_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
