# Generated by Django 6.0.3 on 2026-03-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_options_remove_album_featured_artists_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at']},
        ),
    ]
