# Generated by Django 6.0.3 on 2026-03-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_likedalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Podcast Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('host_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='podcasts/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('plays_count', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='music.language')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='music.podcastcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('episode_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('guest_names', models.CharField(blank=True, max_length=240)),
                ('audio_file', models.FileField(upload_to='podcasts/episodes/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('plays_count', models.PositiveIntegerField(default=0)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='music.podcast')),
            ],
            options={
                'ordering': ['podcast_id', 'episode_number', 'id'],
                'unique_together': {('podcast', 'episode_number')},
            },
        ),
    ]
